### PR TITLE
Added Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**
Hebrew translation added before pt.

### CODE REVIEW

**Comment by tuxfuxch** [comment]
hey yarons!
first of all, thanks a lot! that's amazing! Unfortunately the next release will have changes in the language handling. not sure how, since i didn't get to run what i planned so far. 
The translation is now made via the platform transifex. I'll be happy to merge your changes into transifex. There are also some new strings to translate for the next version. Are you willing to contribute via transifex in future, i would be happy to add you as a translator, but would need an email adress from you, and you would have to create an account. (you can also login in transifex with your github account and ask for beeing a translatior i think).
Also, i would like to not merge your patch over github (i messed up things sorry) and i would include your changes manually for the next release.

furthermore, i saw there are no changes in the stylesheet. that was ment as a hint for me? no problem, i can look into that.

**Comment by yarons** [comment]
LOL, thank you very much for the quick response.
I can certainly look into the RTL CSS thing but I need your cooperation with adding the appropriate support (adding a dir parameter to the translation where I can set the directionality).

How would you like me to submit it?

Kind regards,
Yaron.

**Comment by tuxfuxch** [comment]
Hey Yaros,
in my local copy, the work i am doing - as i said - it's a new language system. translations are made now with transifex.com. i tried it with hebrew, and to me it looks kinda good. on the under hand, since i don't understand a thing i am sure i am missing the point where it's wrong or unlogic. so yeah, help is appresiated.
first of all: i did not really get what you ment with the words in brackets (i am, as you surely know by now, not a native english speaker).
i think we face two problems now: the first you don't know yet: i transfered your work to transifex. i did not manage all of it, and i am very sure that i messed up a looooot of things. i would really appreciate if you could give me your email address (private message or write to 
tuxfux       at    gmail     dot   com) that i can invite you.
only if you want to, because you have to make a login or you can use the github login, in that case you would have to make first the transifex account and give me your login email adress (i only guess that). 
there you would have to fix my failure.

after that (i think, please correct me if i am wrong) we have to look how to change it. i guess that the order of (for example) the movie information is worng:
instead of " Year: 2008 " it would be in hebrew first "2008 :Year". is that right? There we have  a problem, some things are hard coded and not easy to change as it is now. 
if i am right, i have to look into some stuff. 

Or in other words: some examples would be helpfull to understand.

did i miss the point? i hope not. and i hope i am not asking for too much, since you did a great deal of work already. it's just a bit unlucky that i am switching the system in the same time as you did the work.

**Comment by tuxfuxch** [comment]
Hey Yaros,
in my local copy, the work i am doing - as i said - it's a new language system. translations are made now with transifex.com. i tried it with hebrew, and to me it looks kinda good. on the other hand, since i don't understand a thing, i am surethat  i am missing the point where it's wrong or unlogic. so yeah, help is appresiated.
first of all: i did not really get what you ment with the words in brackets (i am, as you surely know by now, not a native english speaker).
i think we face two problems now: the first you don't know yet: i transfered your work to transifex. i did not manage all of it, and i am very sure that i messed up a looooot of things. i would really appreciate if you could give me your email address (private message or write to 
tuxfux       at    gmail     dot   com) that i can invite you.
only if you want to, because you have to make a login or you can use the github login, in that case you would have to make first the transifex account and give me your login email adress (i only guess that). 
there you would have to fix my failure.

after that (i think, please correct me if i am wrong) we have to look how to change it. i guess that the order of (for example) the movie information is worng:
instead of " Year: 2008 " it would be in hebrew first "2008 :Year". is that right? There we have  a problem, some things are hard coded and not easy to change as it is now. 
if i am right, i have to look into some stuff. 

Or in other words: some examples would be helpfull to understand.

did i miss the point? i hope not. and i hope i am not asking for too much, since you did a great deal of work already. it's just a bit unlucky that i am switching the system in the same time as you did the work.

EDIT: i think if numbers combined with words need another order, i can manage that with the new language system (i use i18next)

**Pull request merged**
